export const questions = [
    { text: "Esse ipsum dolore cillum consectetur culpa ullamco dolor. ", correctAnswer: true },
    { text: "Adipisicing cupidatat et minim anim anim eiusmod ad cupidatat exercitation fugiat.2", correctAnswer: false },
    { text: "Consectetur commodo irure non ullamco nostrud minim tempor incididunt irure Lorem veniam veniam dolore sint.3", correctAnswer: true },
    { text: "Nulla anim laboris cillum nisi non consectetur non non sunt velit duis voluptate laboris cupidatat.4", correctAnswer: false },
    { text: "Minim sunt excepteur aliqua magna non ullamco qui laboris nisi.5", correctAnswer: true },
    { text: "Proident aliquip incididunt nulla quis pariatur mollit eiusmod veniam minim dolore mollit consectetur pariatur reprehenderit.6", correctAnswer: false },
    { text: "Adipisicing esse Lorem anim enim pariatur qui id.7", correctAnswer: true },
    { text: "Consequat voluptate enim consectetur amet cillum.8", correctAnswer: false },
    { text: "Aliqua commodo esse veniam consequat voluptate incididunt nostrud et.9", correctAnswer: true },
    { text: "Non culpa non aute reprehenderit do.10", correctAnswer: false },
    { text: "Minim enim consequat excepteur duis.11", correctAnswer: true },
    { text: "Ipsum ex pariatur veniam ex est voluptate deserunt aute velit laboris veniam.12", correctAnswer: false },
    { text: "In eu deserunt cillum adipisicing fugiat cupidatat eu.13", correctAnswer: true },
    { text: "Quis culpa nisi ipsum quis adipisicing sunt sint ullamco et aute anim ut esse.14", correctAnswer: false },
    { text: "Culpa nisi Lorem dolore enim.15", correctAnswer: true },
    { text: "Id magna enim mollit esse ut sit velit duis.16", correctAnswer: false },
    { text: "Non aliquip laborum ex exercitation laboris Lorem occaecat adipisicing esse.17", correctAnswer: true },
    { text: "Est elit cillum Lorem consectetur.18", correctAnswer: false },
    { text: "In do aute ipsum occaecat elit nisi eu consectetur id magna.19", correctAnswer: true },
    { text: "Pariatur in reprehenderit veniam qui.20", correctAnswer: false },
    { text: "Anim deserunt exercitation elit nulla ad fugiat adipisicing.21", correctAnswer: true },
    { text: "Non proident laborum occaecat proident quis ipsum incididunt ad exercitation adipisicing excepteur veniam quis aute.22", correctAnswer: false },
    { text: "Ea quis duis consequat consectetur.23", correctAnswer: true },
    { text: "Deserunt cillum velit amet cillum et fugiat commodo id deserunt occaecat est tempor minim nulla.24", correctAnswer: false },
    { text: "Labore do sit duis anim.25", correctAnswer: true },
    { text: "Irure officia enim officia sint labore do.26", correctAnswer: false },
    { text: "Cillum consequat sit quis ut occaecat quis ut ut proident ex ex reprehenderit ut.27", correctAnswer: true },
    { text: "Exercitation fugiat voluptate officia non pariatur enim magna tempor irure non fugiat.28", correctAnswer: false },
    { text: "Voluptate est ex occaecat officia.29", correctAnswer: true },
    { text: "Consectetur qui irure commodo commodo.30", correctAnswer: false },
    { text: "Ut est occaecat dolore sit excepteur minim excepteur esse eu sit.31", corectAnswer: true },
    { text: "Lorem ullamco officia aute eiusmod ex enim dolore eiusmod voluptate.32", correctAnswer: false },
    { text: "Enim nostrud enim non sunt culpa ipsum quis ut.33", correctAnswer: true },
    { text: "Eu consectetur do nulla laboris fugiat.34", correctAnswer: false },
    { text: "Fugiat magna qui ex cillum elit in elit fugiat qui nulla ipsum deserunt.35", correctAnswer: true },
    { text: "Incididunt dolor magna id ea culpa laborum aliquip do consectetur velit eiusmod quis minim commodo.36", correctAnswer: false },
    { text: "Elit fugiat consequat dolor nulla veniam aliqua.37", correctAnswer: true },
    { text: "Tempor id id duis occaecat mollit ut aliqua sit qui quis minim in.38", correctAnswer: false },
    { text: "Culpa cupidatat cillum laboris reprehenderit ad mollit aute laborum aute labore ullamco esse.39", correctAnswer: true },
    { text: "Tempor incididunt aute in ex.40", correctAnswer: false },
    { text: "Sit consectetur deserunt velit commodo laboris aliquip.41", correctAnswer: true },
    { text: "Laboris cillum sint et ut.42", correctAnswer: false },
]